"""Constants for code generation from OpenAPI spec."""

# Code generation header
COMMENT_HEADER = "# @generated by codegen. DO NOT EDIT BY HAND"

# Activity type version mappings
# Each entry maps to a tuple of (versioned_type, intent_type, result_type)
VERSIONED_ACTIVITY_TYPES = {
    "ACTIVITY_TYPE_CREATE_AUTHENTICATORS": (
        "ACTIVITY_TYPE_CREATE_AUTHENTICATORS_V2",
        "v1CreateAuthenticatorsIntentV2",
        "v1CreateAuthenticatorsResult",
    ),
    "ACTIVITY_TYPE_CREATE_API_KEYS": (
        "ACTIVITY_TYPE_CREATE_API_KEYS_V2",
        "v1CreateApiKeysIntentV2",
        "v1CreateApiKeysResult",
    ),
    "ACTIVITY_TYPE_CREATE_POLICY": (
        "ACTIVITY_TYPE_CREATE_POLICY_V3",
        "v1CreatePolicyIntentV3",
        "v1CreatePolicyResult",
    ),
    "ACTIVITY_TYPE_CREATE_PRIVATE_KEYS": (
        "ACTIVITY_TYPE_CREATE_PRIVATE_KEYS_V2",
        "v1CreatePrivateKeysIntentV2",
        "v1CreatePrivateKeysResultV2",
    ),
    "ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION": (
        "ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V7",
        "v1CreateSubOrganizationIntentV7",
        "v1CreateSubOrganizationResultV7",
    ),
    "ACTIVITY_TYPE_CREATE_USERS": (
        "ACTIVITY_TYPE_CREATE_USERS_V3",
        "v1CreateUsersIntentV3",
        "v1CreateUsersResult",
    ),
    "ACTIVITY_TYPE_SIGN_RAW_PAYLOAD": (
        "ACTIVITY_TYPE_SIGN_RAW_PAYLOAD_V2",
        "v1SignRawPayloadIntentV2",
        "v1SignRawPayloadResult",
    ),
    "ACTIVITY_TYPE_SIGN_TRANSACTION": (
        "ACTIVITY_TYPE_SIGN_TRANSACTION_V2",
        "v1SignTransactionIntentV2",
        "v1SignTransactionResult",
    ),
    "ACTIVITY_TYPE_EMAIL_AUTH": (
        "ACTIVITY_TYPE_EMAIL_AUTH_V3",
        "v1EmailAuthIntentV3",
        "v1EmailAuthResult",
    ),
    "ACTIVITY_TYPE_CREATE_READ_WRITE_SESSION": (
        "ACTIVITY_TYPE_CREATE_READ_WRITE_SESSION_V2",
        "v1CreateReadWriteSessionIntentV2",
        "v1CreateReadWriteSessionResultV2",
    ),
    "ACTIVITY_TYPE_UPDATE_POLICY": (
        "ACTIVITY_TYPE_UPDATE_POLICY_V2",
        "v1UpdatePolicyIntentV2",
        "v1UpdatePolicyResultV2",
    ),
    "ACTIVITY_TYPE_INIT_OTP_AUTH": (
        "ACTIVITY_TYPE_INIT_OTP_AUTH_V3",
        "v1InitOtpAuthIntentV3",
        "v1InitOtpAuthResultV2",
    ),
    "ACTIVITY_TYPE_INIT_USER_EMAIL_RECOVERY": (
        "ACTIVITY_TYPE_INIT_USER_EMAIL_RECOVERY_V2",
        "v1InitUserEmailRecoveryIntentV2",
        "v1InitUserEmailRecoveryResult",
    ),
    "ACTIVITY_TYPE_INIT_OTP": (
        "ACTIVITY_TYPE_INIT_OTP_V2",
        "v1InitOtpIntentV2",
        "v1InitOtpResult",
    ),
}

# Methods that have only optional parameters
METHODS_WITH_ONLY_OPTIONAL_PARAMETERS = [
    "getActivities",
    "getApiKeys",
    "getOrganization",
    "getPolicies",
    "getPrivateKeys",
    "getSubOrgIds",
    "getUsers",
    "getWallets",
    "getWhoami",
    "listPrivateKeys",
    "listUserTags",
]

# Terminal activity statuses
TERMINAL_ACTIVITY_STATUSES = [
    "ACTIVITY_STATUS_COMPLETED",
    "ACTIVITY_STATUS_FAILED",
    "ACTIVITY_STATUS_CONSENSUS_NEEDED",
    "ACTIVITY_STATUS_REJECTED",
]
