name: "Setup Python"
description: "Install Python toolchain and dependencies"

inputs:
  python-version:
    description: "Python version to use"
    required: false
    default: "3.10"

runs:
  using: "composite"

  steps:
    # https://github.com/actions/setup-python
    - name: Install Python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Upgrade pip
      run: python -m pip install --upgrade pip
      shell: bash

    - name: Get pip cache directory
      id: pip-cache-dir
      run: |
        echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      shell: bash

    # https://github.com/actions/cache
    - name: Setup pip cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ${{ steps.pip-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install -e .[dev]
        pip install -e ./packages/sdk-types[dev]
        pip install -e ./packages/api-key-stamper[dev]
        pip install -e ./packages/http[dev]
      shell: bash
